platform :ios, '8.0'

inhibit_all_warnings!

def shared_first_pods
    pod 'AFNetworking', '~> 3.1.0'
    # pod 'PromiseKit', '~> 1.6'
    pod 'WebViewJavascriptBridge'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'WebViewJavascriptBridge'
end

def shared_second_pods
    pod 'ReactiveCocoa', '~> 2.5'
end

target 'RNProject' do
    shared_first_pods
    shared_second_pods

end

# target 'YDTInterview' do
#     shared_first_pods
#     shared_second_pods
# end
#
# target 'YDTMonitor' do
#     shared_first_pods
#     shared_second_pods
# end
#
# target 'YDTLibraryStatic' do
#     shared_first_pods
# end
